baseURL = "http://examplesite.org"
disableLanguages = ["french", "Fr", "fr"]
disqusShortname = "educenter"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Educenter | hugo education template"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "teacher"
name = "teacher"
[[menu.footer]]
URL = "event"
name = "event"
[[menu.footer]]
URL = "scholarship"
name = "scholarship"
[[menu.footer]]
URL = "research"
name = "research"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "course"
name = "course"
weight = 2
[[menu.main]]
URL = "contact"
name = "contact"
weight = 5
[params]
address = ""
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "admin@thinktoolsforchildren.org"
google_analitycs_id = ""
logo = "/images/think-tools-logo.jpeg"
mobile = ""
social = []
top_header = false
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
