---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: directory
  path: dataworkz/content/english/blog
  label: Post (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Team
- type: directory
  path: dataworkz/content/english/team
  label: Team (en)
  create: documents
  match: "**/*"
  templates:
  - team
- type: heading
  label: Course
- type: directory
  path: dataworkz/content/english/course
  label: Course (en)
  create: documents
  match: "**/*"
  templates:
  - course
- type: heading
  label: Event
- type: directory
  path: dataworkz/content/english/event
  label: Event (en)
  create: all
  match: "**/*"
  templates:
  - event
- type: heading
  label: Timeline
- type: directory
  path: dataworkz/content/english/timeline
  label: Timeline (en)
  create: all
  match: "**/*"
  templates:
  - timeline
- type: heading
  label: Solutions
- type: directory
  path: dataworkz/content/english/solutions
  label: Solutions (en)
  create: all
  match: "**/*"
  templates:
  - solutions
- type: heading
  label: Others Pages
- type: directory
  path: dataworkz/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: dataworkz/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: dataworkz/content/english/pages
  label: Created Pages (en)
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: dataworkz/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: dataworkz/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: dataworkz/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: dataworkz
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
